Adjust/enhance some tests
jenkinsci/lib-file-leak-detector pull request #113
Opened 2022-09-04 20:32 UTC by centic9

Print out more information on failure
Mention that some tests need to run with installed agent
Add a few more tests
Some classes are not available when running tests on Windows

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [o] Link to relevant issues in GitHub or Jira
- [o] Link to relevant pull requests, esp. upstream and downstream changes
- [o] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-09-04 21:41 UTC, MarkEWaite requested changes
Thanks so much for improving the tests.  One of the tests fails on my Linux environment.  The same test passes on the master branch.  Could you investigate and resolve the test failure?

2022-09-04 21:41 UTC, MarkEWaite commented on src/test/java/org/kohsuke/file_leak_detector/instrumented/FileDemo.java
> +            assertThat("Did not have the expected type of 'marker' object: " + obj,
This assertion fails when I run the test on my Red Hat Enterprise Linux 8 computer with Eclipse Adoptium Java 11.0.16.1 and Apache Maven 3.8.6 using the command line:

```
$ mvn -version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /home/mwaite/tools/apache-maven-3.8.6
Java version: 11.0.16.1, vendor: Eclipse Adoptium, runtime: /home/mwaite/tools/jdk-11.0.16.1+1
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-372.19.1.el8_6.x86_64", arch: "amd64", family: "unix"
$ mvn clean verify
[ERROR] Failures:
[ERROR]   FileDemo.openCloseFileLines:262 Did not have the expected type of 'marker' object: sun.net.www.protocol.jar.URLJarFile@7b69c6ba
Expected: an instance of java.nio.channels.SeekableByteChannel
     but: <sun.net.www.protocol.jar.URLJarFile@7b69c6ba> is a sun.net.www.protocol.jar.URLJarFile
[INFO]
[ERROR] Tests run: 14, Failures: 1, Errors: 0, Skipped: 0
```

The same failure is seen with JDK 11.0.16 that is available with RHEL 8 as an RPM package.

The same command line, operating system, and Java version run the test successfully from the master branch. 

The failure is not seen with JDK 17.0.4.1 with this pull request.

2022-09-05 06:41 UTC, centic9 commented on src/test/java/org/kohsuke/file_leak_detector/instrumented/FileDemo.java
> +            assertThat("Did not have the expected type of 'marker' object: " + obj,
This is a very strange flakiness that is likely not introduced by my changes. 

It works at times, but fails with this sometimes. Seems to be some race condition with some jar-file loading in other threads or similar.

I can try to narrow it down a bit more.

2022-09-05 08:09 UTC, centic9 commented on src/test/java/org/kohsuke/file_leak_detector/instrumented/FileDemo.java
> +            assertThat("Did not have the expected type of 'marker' object: " + obj,
Seems to be a close() via a Finalizer done concurrently sometimes. 

I now exclude closing of URLJarFile in the test to avoid this flakiness.

2022-09-05 12:15 UTC, MarkEWaite approved these changes
I've confirmed that the machine that previously showed consistent failures did not show any failure with 10 runs of `mvn clean verify`.  Also confirmed no failures with 10 runs on a second machine.  Thanks very much!

Optional comment based on formatting.  Whether or not that comment is applied, I plan to merge this after 24 hours unless others raise an objection.

2022-09-05 12:15 UTC, MarkEWaite commented on src/test/java/org/kohsuke/file_leak_detector/instrumented/FileDemo.java
> +
Thanks very much!.  Optional indentation change to make it consistent with the indentation immediately below it.
```suggestion
           // sometimes java.util.zip.ZipFile$CleanableResource$FinalizableResource.finalize()
           // will kick in and will close a ZipFile, thus we ignore the corresponding objects here
           if (obj.getClass().getSimpleName().contains("URLJarFile")) {
               return;
           }

```

2022-09-05 18:02 UTC, merged